/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package homework03

import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking

// Task 4
suspend fun main(vararg args: String) {
    if (args.isEmpty())
        println("Usage: ...names\nNames of subreddits were expected (e.g. Kotlin, Cpp or Python)")
    val start = System.currentTimeMillis()
    runBlocking {
        args.forEach {
            launch {
                RedditClient().parseSubreddit(it)
            }
        }
    }
    println((System.currentTimeMillis() - start) / 1000)
}
